data/cards-blood.cfg
data/classes/creature.cfg

Adds "pyre zombie", there was a reddit thread here: https://www.reddit.com/r/ArgentumAge/comments/2ztv3p/card_idea_pyre_zombie/

Pyre zombie card

---

data/cards-expansion_set-meldingways.cfg
data/cards-scrolls.cfg

let Stoic use energy instead of channel.
Changed 2 cards' texts, using the phrase "spend an action" instead

minor card changes

---

data/classes/player.cfg

Revert "Support for player.this_turn_effect"

---

data/objects/card.cfg

Changes IFs to SWITCHes in order to accomodate 1-5 school cards, for both border drawing and card coloring gradient.

Update support for 1-5 school card coloring

---

data/classes/bot_eval.cfg
data/classes/rival_decks.cfg

1. Adjusted the scores of the evaluation. Income and hand size should
shall be deemed more important.
2. Adjusted Catherine's mono-Materia deck, reduced the number of the
cards that she can't use well, and added more Mercenary and Loyal Guard to
make she play on curve more easily.

Modify eval() function, changed Catherine's deck

---

data/puzzles.cfg

Adjusted trophy value instead of shaper health. Now it works, with a
only answer.

Refined puzzle2

---

data/puzzles.cfg

Added a Minerva Puzzle, and refined the AeMa puzzle again.

Another Puzzle

---

data/puzzles.cfg

An entropia puzzle; adjusted the 2nd puzzle, denied an extra solution

A 3rd puzzle

---

data/puzzles.cfg

Now there is only one solution

made Entropia Puzzle a bit harder

---

data/classes/rival_decks.cfg
data/rivals.cfg

Every Rival has at least 3 decks now.

3 More Rival Decks

---

data/puzzles.cfg

An easy puzzle

---

data/classes/citadel.cfg
module.cfg

Now the cards cost around 1/5 the gold. Less grind for players.

Reduced the cost of cards

---

data/cards-blood.cfg
data/cards-gold.cfg

ghost to 5(2),
tactical maneuver to 3(1)

Increase cost of two cards

---

data/puzzles.cfg

After the Blood Altar change, the puzzle is no longer fit.

Remove Entropia Puzzle 1

---

data/puzzles.cfg

Added a puzzle that teach players the fizzle rule of Chain Lightning and
Outsmart the Guards as spell counter.

Added a tutorial-puzzle

---

data/objects/intro_animation_controller.cfg
data/objects/puzzle_lobby_controller.cfg
data/puzzles.cfg

1. Rephrased a tip about loyalty level in tutorial.
2. Added 2 instructional puzzles; haven't added text yet.
3. Changed title and portraits of puzzles. And tutorial puzzles all use Temulina as the opponent now.

Tutorial and Puzzles

---

data/puzzles.cfg

A quick fix to ensure that the puzzle Response Chain can be only solved
in the intended way

A quick puzzle fix

---

data/puzzles.cfg

A new puzzle

---

data/classes/bot.cfg
data/objects/citadel_controller.cfg

Bots don't discard when should_wait, and a debug command
see_enemy_hand()

Fix bot discarding when waiting

---

data/cards-expansion_set-experimental_1.cfg

Adjust the set name so cards correctly enters the game.

Fixing the Set Experimental 1

---

data/cards-expansion_set-experimental_1.cfg

Thousand Arrow: Materia/Entropia damaging spell

A New Card to Experimental1

---

data/cards-expansion_set-experimental_1.cfg

Archer, Promised Shelter and Master Assassin

3 new cards to Exp1

---

data/cards-expansion_set-experimental_1.cfg
data/cards-gold.cfg

Forztezza Movente, Silver Portal, Mind Shock, Militia

4 new cards

---

data/cards-expansion_set-experimental_1.cfg

Divine Illumination, Relinquisher and Warrior of Light

3 new cards in Exp1

---

data/cards-expansion_set-experimental_1.cfg

2 new cards and some balances.

Working on Exp1

---

data/cards-expansion_set-experimental_1.cfg

Radius 1 version of 2-mana lands

4 new cards to Exp1 set

---

data/cards-aether.cfg
data/classes/creature.cfg
data/test-cases.cfg

Add proposal of fix for issue in https://github.com/davewx7/citadel/pull/106 (_Possible error while silencing `Guardian Tunneler`?_) in this separate branch just in case I overlooked something.

Add proposal of fix for issue in PR#106

---

data/objects/player_profile_pane.cfg

Compound PR... only applies if https://github.com/anura-engine/anura/pull/198 is to be embraced.

Adjust font size for player's username in lobby.

---

.gitignore
data/cards-entropia.cfg
data/particles/smoke_candidate.cfg

Add the case described by https://github.com/davewx7/citadel/issues/142.

Particle system problem demo.

---

data/cards-minerva.cfg

Source is forged with parts from 'Traitor' (Minerva) and 'Ghost'
(Entropia).

Add card, moves any creature back to owner's hand.

---

data/maps.cfg

Add five laned hourglass map.

---

data/classes/game_state.cfg
data/maps.cfg

I coded a way to define random hexes in the `data/maps.cfg` doc. I hope you think of it as acceptable idea. It only shows up in the single player window by now, so it is not a great deal of a change.
Cheers and Regards,

Add one randomly pre-terraformed map.

---

data/cards-expansion_set-shatteredAlliances.cfg
data/classes/card_base.cfg
data/classes/creature.cfg

I irresponsibly got @pacnutek into using `creature.is_regular_creature` for https://github.com/davewx7/citadel/pull/154 and now I'm not sure of that signature to be even completely implemented 😬, so this is my try into amending it.

Fix syntax error in `Quantum in oculis deorum`.

---

data/objects/choose_deck_controller.cfg
data/starting-decks.cfg
data/types.cfg

Put similar (similar in school) decks together in the starter decks selector.
Without this change:
With this change:
Cheers and Regards,

Sort starter decks associatively by school.

---

data/cards-expansion_set-shatteredAlliances.cfg
data/objects/library_controller.cfg
data/objects/library_scroll_view_controller.cfg

This fixes a bug reported by predator8bit on Discord.
Changed zorder for combo_controller and cards in "scroll view".
The zorder of cards in "scroll view" was unnecessary high. it is lower now.

Fix combo list and a card

---

data/objects/choose_deck_controller.cfg
data/objects/citadel_controller.cfg
data/objects/news_updates_pane.cfg
data/objects/player_profile_pane.cfg
data/objects/quest_display.cfg
data/objects/title_controller.cfg
data/objects/widgets/title_option_widget.cfg

Major UI rework including Home Screen, Store, Single/Multiplayer screens and probably some other elements. This is a long-term project. It'll take some time to get finished. Hopefully no changes to anura will be needed.
Don't merge.

Game UI rework

---

data/cards-aether.cfg
data/cards-entropia.cfg
data/cards-expansion_set-meldingways.cfg
data/cards-orphaned.cfg
data/cards-void.cfg
data/classes/bot_evolutionary.cfg
data/classes/bot_evolutionary2.cfg
data/classes/bot_intro.cfg
data/classes/citadel.cfg
data/classes/crypt.cfg
data/classes/game_state.cfg
data/classes/player.cfg
data/classes/tips.cfg
data/classes/tutorial_intro.cfg
data/objects/card.cfg
data/objects/citadel_controller.cfg
data/objects/creature.cfg
data/puzzles.cfg
data/test-cases.cfg

Introduce a new class crypt and crypt.entry to manage what was formerly contained in the discard_pile for played spells and the graveyard for creatures.

Crypt refactor

---

data/objects/library_controller.cfg

My own attempt at dealing with https://github.com/davewx7/citadel/issues/236.

Respawn Library Book View arrows.

---

README.md

Should make it easier for new players to find support

Add a link to the discord server in the README

---

data/cards-minerva.cfg

Fix typo in Dream Eater description
