data/cards-food.cfg, data/classes/bot.cfg, data/classes/bot_evolutionary3.cfg, data/classes/game.cfg, data/objects/citadel_controller.cfg, data/objects/end_turn_button.cfg
TODO: This seems to be working great now, the one thing I don't like is the following:
In many games vs AI, the game ends when the AI runs out of cards. Then your creatures march forwards to break the seals. Before this commit, on the turn when you would win by breaking the seals, you don't have to do anything because the creatures move on their own at the start of your turn. This is very smooth.
After this commit, if you have a response card playable in your hand, like a wisp, or if you have Hold Responses on, you still will have to press end turn once more than necessary, because you still get to respond to the AI's end of turn (when it cannot do anything). You have to do this, then you win immediately when your creatures move.
What I would like to do is to add a check, if this is the …
=> Refactor timings iii

data/classes/game.cfg
"state_based_actions_interal" can sometimes recursively call
"state_based_actions". If this happens, it results in many
instances of the "do_moves" command seequence when the recursion
unwinds, since it will be called once at the tail of each call to
"state_based_actions".
After this commit, the moves sequence should only be called once.
Since repeated calls to it won't do anything, it shouldn't change
anything except make the control flow simpler.
=> change the end_of_turn sequence, to avoid repeatedly calling moves

data/cards-gold.cfg
Tried to add this card, however it seems there is a bug in the citadel networking code. If a card prompts the *other* player to make a choice, it seems that player becomes unresponsive and disconnects from the server, while the first player immediately sees the result that they chose something, so the clients become out of sync.
=> add "taxes and tolls" (don't merge)

data/objects/card.cfg, data/objects/combo_controller.cfg, data/objects/library_controller.cfg, data/objects/title_multiplayer_controller.cfg
Enabled right-clicking on a card to remove it from deck.
Modified multiplayer mode button's size, so the "Players vs Players" text doesn't stretch out; 
Modified the position of the first deck entry, so it doesn't overlap with deck title;
=> Small interface tweaks

data/classes/card_base.cfg, data/objects/citadel_controller.cfg
Added a property of "default_channeled_mana", which can be set to define
the max mana a card would default channel. Mainly used to let
upper-limited channeling effects more friendly to use.
=> card property: "default_channeled_mana"

data/classes/player.cfg
added the support for player.apply_effect_until_end_of_turn
player.this_turn_effects is the same as creature.this_turn_effects
and player.this_turn_effects_compensate is added to support operating on
lists, because you can't add(var, -{list}) with FFL.
also, a property of base_resource_level, which is used by one of my
cards that temporally adjust a player's school levels.
=> Support for player.this_turn_effect

data/classes/bot_eval.cfg
1. Reduced the value of players' life points when they're above 20, to
try to discourage ai from throwing fireballs in early games.
2. Added ai's school loyalty into game state evaluation.
=> modify eval function

data/classes/rival_decks.cfg, data/rivals.cfg
Catherine Materia, Meira AetherMinerva and Grizzis Gaea.
The 3 decks all have 50 cards now, and they're easier for AI to use
well.
=> 3 Rival Decks

data/cards-food.cfg
Buff Treant Sapling's health by 1, so it's no longer an inferior version
of Wolf Rider.
=> Buff Treant Sapling to 2/3

data/cards-blood.cfg
they no longer work on buildings.
=> Changed Kelos and Dark Fate

data/classes/rival_decks.cfg
removed Thunderers, since AI doesn't understand Reload.
=> Modified Rival Decks

data/objects/deck_preview_widget.cfg, data/objects/library_archive_controller.cfg, data/objects/library_controller.cfg
1. A prompt before deleting vault decks;
2. Prevent adding cards to a 50-card deck by clicking on a deck entry. 
3. Preview in deck selection shows the number of cards in each type.
=> improve deck UI

data/objects/effects/hypothermia_creature_effect.cfg
It was being incorrectly shown for enemy creatures.
=> Fixup Hypothermia effect positioning

data/object_prototypes/impact_effect_base.cfg
This fixes a crash when casting cards such as Fireball on a player.
=> Allow impact_effect_base to effect player_avatar objects

data/test-cases.cfg
Add test for (a strange?) situation regarding a silenced unengaged 'Guardian Tunneler' to end up with a -4 armor bonus.
=> Possible error while silencing `Guardian Tunneler`?

data/test-cases.cfg
I think something got broken with _occupied_ lands click; related to an activation of some strict mode (don't really know how many modes exist for FFL, less how many them are _strict_ (is that something similar to the JS strict mode..?) or how strict is any of them), from what I read in Anura console output.
Fix for the supposed trouble already coded, will show in a subsequent PR.
This was suddenly and discovered while doing thorough testing of some minor Anura changes subsequent PR.
Cheers and regards,
=> Add playable test for occupied lands.

data/objects/creature.cfg, data/test-cases.cfg
Add proposal of fix for issue in #108 (Anura assertion failed on clicking an _occupied_ land) in separate branch to help treating the problem and the proposed solution separately.
It seems to me the _crash_ problem comes from the activation of a strict mode (somewhere, I don't know where nor when) without a fully exhaustive check of all sources. I guess it is more appropriate fixing it forwards rather than reverting back the mode change.
Obviously this type of issues can be wiped out with full coverage, but am not at all positioned to make particular advice on that topic.
Cheers and regards,
=> Add proposal of fix for issue in PR#108

data/objects/card.cfg
Reduce dashes size in card placeholders while some else sorts out a
more elaborate card placeholder... if I am not mistaken the current
plan is to have the normal card back, but with a lot of transparency.
See result:
=> Reduce dashes size in card placeholders.

data/campaign-dialog/28ef14b4b257405e84ea58b3a49b1bc5.cfg
The Guardsman, meant to be a beginner challenge right out of Shoalstill, may be a bit overpowered. The problem is having all those cheap efficient units (particularly the Loyal Guard) creates an incredible amount of pressure in the early-to-mid game.
simple fix: don't add or remove card types, just make it a <50 deck so
he can't spam units of the same type.
(I playtested this and it does seem to play out more fairly.)
=>  give Guardsman no more than 3 of each card

data/cards-adjustments.cfg, data/cards-colorless.cfg
Motivation: `Monument` as seen at https://github.com/davewx7/citadel/pull/131.
That is:
Before this change:
After this change:
This makes: 
or:
Cheers and Regards,
=> Adjust `Rihn's monument`.

data/cards-aether.cfg, data/cards-entropia.cfg
This was the long lived previous iteration:
This is the current iteration, after the effects were requested to be more subtle:
I find that an excessive subtle, I am proposing them to be like these:
Cheers,
=> Propose further iteration in the obelisks visuals.

data/help-abilities.cfg
`Lethal` is not currently being against buildings, and I think that is
OK, so remove buildings from the definition of 'enemy' by specifying
`Lethal` destroys `creature` enemies.
=> Adapt `Lethal` tip to current facts.

data/objects/rival_pane.cfg, data/objects/title_controller.cfg
data/objects/rival_pane.cfg: If the mode is off line, remove the
'Multiplayer Challenge' from the list of rivals. Make the 'Random
Rival' the default rival for the off line mode.
data/objects/title_controller.cfg: If the mode is off line, change the
'Multiplayer' label for something like 'Single Player'.
=> Label changes in the off line mode.

data/test-cases.cfg
Adds playable test for pointing out 'Deception' and 'Traitor' are
showing a 'death skull' effect (briefly) on the creature they are
moving to a player's hand. Assuming that effect could be undesired.
=> Point out candidate visual bug.

data/objects/card.cfg
In the mid term I want to propose a noticeable particles for _shadow deck cards_. In the meanwhile, I thought it could be better to have it in red, more obvious to the newcomer while not awful to the tenured (I... guess...). I don't know sh about colors, but this neat tool http://paletton.com/#uid=2000u0krPopiwvknks1uCk1CHeV was telling green is complementary, so I added it to replace the white shadow of playable card. Why not..? I'm not sure, but it's like the green glow for playable card has already been suggested. 
I'm aware that green glow on playable card is something present in other CCGs with _arguably not so dark thematic, ambience and storytelling_, so if you feel this doesn't fit well with the lore, just discard or silently ignore.
I don't really care that much if the playable …
=> Proposing color changes in card shadows while in hand.

data/objects/card.cfg, data/objects/library_book_view_controller.cfg, data/objects/library_controller.cfg, data/objects/library_deck_summary.cfg, data/objects/library_scroll_view_controller.cfg
- Changed the card grid in "book view". The grid is now 4x2 and not 3x3.
- Made the cards slightly smaller (from 1.5 to 1.4).
- Filter buttons were moved up and set on the same line.
- Filter buttons have changed brightness when mouse hovers over them.
- Name and icon of active school were enlarged and rearranged.
- The deck overview card was slightly changed (stats moved by few px).
I apologize for a lot of whitespace mess my editor did.
=> Library UI overhaul

data/cards-aether.cfg
The icon changed to be more consistent with other cards which have abilities triggered by death.
It solves issue #208 – _More adecuate icon for the triggered ability of the Rihn's Martyr card_
=> Trigger-death icon added to Rihn's Martyr's ability

data/cards-expansion_set-experimental_1.cfg
Should fix #254.
It looks like either at some point `info.player` might have
been synonymous for `info.player_index`, or this card could
have never worked OK. `info.player` is `null`, which is being
implicitly promoted to `0`, giving the mana bonus always to
player 0. This explains the misbehavior described by SkippyQ.
I actually checked that this change fixes the problem.
=> Update Divine Illumination spell.
